services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: comfyUI_tuner
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - COMFYUI_ADDRESS=host.docker.internal:8188
      - MONGO_URI=mongodb://mongodb:27017/
      - FLASK_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./backend/:/backend
      - ../ComfyUI:/backend/ComfyUI
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongodb:
    image: mongo:8.0.6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    command: ["mongod", "--config", "/etc/mongod.conf"]

  frontend:
    build:
      context: ./frontend
    container_name: comfyUI_tuner_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - web
      - mongodb

volumes:
  mongo_data:
