version: '3.8'

services:
  web:
    build: .
    container_name: comfyUI_tuner
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - COMFYUI_ADDRESS=192.168.1.1:8188
      - MONGO_URI=mongodb://mongodb:27017/
      - FLASK_ENV=development
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /home/sam/Documents/qlab/ComfyUI:/app/ComfyUI
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    command: ["mongod", "--config", "/etc/mongod.conf"]

volumes:
  mongo_data:
