name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        cd backend
        export PYTHONPATH=$(pwd)
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        cd backend
        export PYTHONPATH=$(pwd)
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        cd backend
        export PYTHONPATH=$(pwd)
        pytest --cov=app --cov-report=term --cov-report=xml --cov-report=html
    
    - name: Display coverage report summary
      run: |
        cd backend
        coverage report

    - name: Display coverage report in detail
      run: |
        cd backend
        coverage html
        cat htmlcov/index.html
